### ISSUE TITLE
Running issue with main.py on Mac 

### ISSUE THREAD

**Issue by weiming9115** [pressel/pycles#46]
Hi, pycles team,

I installed the model by following the instruction for Mac, but I had trouble when running main.py. 
The following is the error: 

> echidna:pycles willytsai$ mpirun -np 4 python main.py DYCOMS_RF01.in
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 13, in main
    namelist = json.loads(file_namelist)
  File "/Users/willytsai/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/willytsai/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/willytsai/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 37 column 5 (char 728)

It seems like something wrong with the json format, but main.py is exactly the default (https://github.com/pressel/pycles/blob/master/main.py). 
My python version is 3.6.5. Any ideas? Thank you.

**Comment by weiming9115** [comment]
It came from a missing comma in the namelist I modified. Problem solved.
